version: "3.4"

services:

  web:
    image: nginx
    volumes:
      - ./templates:/etc/nginx/templates
    ports:
      - "8080:80"
    depends_on:
      - php

  php:
    image: php:8.0-fpm-alpine
#    build: .

# https://hackernoon.com/nginx-php-docker-how-to-get-php-page-up-with-local-domain-name-ho3x33f6